### ISSUE TITLE
Inserting bulk entries

### ISSUE THREAD

**Issue by temiwale88** [Spaarw/mysql-json#3]
Hello team - thanks for this great package! I'm trying to inserting an array of objects (bulk insert) but not sure how to. Right now, I'm looping over the array and inserting each element (which is an object) but that creates a connection every time and it times out etc. What can I do please? I don't see documentation on what to do. Thanks!

**Comment by Spaarw** [comment]
Hello, 

To insert many objects, you can use a Promise way, like this 


```javascript
// Your Array of Objects to insert
let arrayOfObjects = [
	{id: 1, name: 'test'},
	{id: 2, name: 'lol'},
	{id: 3, name: 'hello'},
	{id: 4, name: 'world'},
	{id: 5, name: 'toto'}
];

// Insert all elements of your arrayOfObjects, one by one
Promise.all(arrayOfObjects.map((object) => {
	return new Promise((resolve, reject) => {
		mysqlJson.insert(tableName, object, (err, response) => {
			if (err) reject(err);
			else resolve(response);
		});
	});
})).then((response) => {
	console.log(response);
	// ALL data are inserted, you can continue here !
}, (err) => {
	console.error(err);
	// An error occured
});
```
I suggest you to learn more about [Javascript Promises here](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Promise)
Hope it helps.

**Comment by temiwale88** [comment]
Resolved! (pun intended). It freaking works. Thank you so much for this! You saved me steps, headaches and lines of code with mysql-to-json. God bless you man! Thanks for the recommendation to learn promises as well! I don't understand them yet but would like to.

**Comment by temiwale88** [comment]
P.s. I think you should add this use case on your npm and github pages.
It's a 'life saver'!

Thanks again for your help!
Elijah
