### ISSUE TITLE
cannot find declaration file for module

### ISSUE THREAD

**Issue by temiwale88** [Spaarw/mysql-json#4]
Hello, 

I'm getting this error for just this module in my NodeJS app. It thinks it's a typescript file?
Could you please share your thoughts on why this might be?
![image](https://user-images.githubusercontent.com/21104282/82747762-4001e800-9d51-11ea-8165-f2d78e219b3d.png)

I found this because I kept getting errors on CRUD operations something like "TypeError: Cannot read property 'update' of undefined".

Thanks!

**Comment by Spaarw** [comment]
Hello,

Are you using typescript, or Javascript ?
Also, are you sure that `mysql-json` package has been well installed inside your `node_modules` folder ?

**Comment by temiwale88** [comment]
I'm using js. It was included in node modules. No worries. I have a
workaround for what I wanted to accomplish. Thanks again!

Elijah
